### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: ExecTrain_exec_sft,ExecTrain_claudegpt_debug_replay
template: qwen
cutoff_len: 8192
max_samples: 50000
overwrite_cache: true
preprocessing_num_workers: 16
tokenized_path: saves/ExecTrain_exec_rej_sampling_claudegpt_debug_replay_qwen

### output
output_dir: saves/qwen/full/ExecTrain_exec_rej_sampling_claudegpt_debug_replay
logging_steps: 10
save_steps: 500
plot_loss: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
overwrite_output_dir: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 30
